Add Custom Global Post Processing
sdslabs/Rootex pull request #515
Opened 2022-01-26 01:59 UTC by Bisht13

2022-01-26 02:00 UTC, Bisht13 commented
@sin3point14 PR review

2022-01-26 21:13 UTC, sin3point14 requested changes

2022-01-26 21:13 UTC, sin3point14 commented on rootex/framework/systems/post_process_system.cpp
> +	}
Why is `PostProcessSystem` needing to access `CameraComponent`?
`CameraComponent` is not owning the CustomPostProcess objects, `m_PostProcess` is.

Simply check if the CustomPostProcessing effect for a the given path is already available with `m_PostProcessor` else create a new object and add it. CameraComponent only needs to know what effects are applied on a specific camera.

2022-01-29 16:15 UTC, sin3point14 approved these changes

2022-01-29 16:15 UTC, merged