Make adding InputSchemes more User friendly
sdslabs/Rootex pull request #549
Opened 2022-02-16 20:30 UTC by Bashar-Ahmed

2022-02-16 20:53 UTC, sin3point14 commented on rootex/framework/scene.cpp
> +		char* keys[] = {
Store all these arrays in InputManager classes. 
Also prefer using https://github.com/sdslabs/Rootex/blob/dev/rootex/common/types.h#L106 for static arrays
Keep the elements `String` as well, comes handy.

2022-02-16 20:53 UTC, sin3point14 commented on rootex/framework/scene.cpp
> +		char name[20] = {};
String

2022-02-16 20:53 UTC, sin3point14 commented on rootex/framework/scene.cpp
> +	if (device == 0)
enums https://github.com/sdslabs/Rootex/blob/dev/rootex/core/input/input_manager.h#L19

2022-02-16 20:53 UTC, sin3point14 commented on rootex/framework/scene.cpp
> +		char* keys[] = {
can we construct this array dynamically by looking and calling `GetButtonName`?
creating an array here seems very risky

2022-02-16 20:53 UTC, sin3point14 commented on rootex/framework/scene.cpp
> +		ImGui::Combo("", &currentKey, keys, ARRAYSIZE(keys));
An empty first argument may give us collision issues, if it needs to be empty, add make it something like: `"##Keyboard Input"

2022-08-05 13:13 UTC, angad-k requested changes
Rename those functions, lgtm otherwise

2022-08-05 13:13 UTC, angad-k commented on rootex/core/input/input_manager.cpp
> +Array<String, 20> InputManager::getPadButtonName()
maybe rename this to `getPadButtonNames`, similar for all others

2022-08-06 19:49 UTC, ChronicallySerious commented on rootex/core/input/input_manager.cpp
> +	Array<String, 23> mouseKeys = {
Making these arrays static will give you a free perf boost

2022-08-09 19:40 UTC, angad-k approved these changes

2022-08-09 19:41 UTC, merged