Particle effect component doc
sdslabs/Rootex pull request #560
Opened 2022-02-21 18:46 UTC by r41k0u

2022-02-21 20:19 UTC, Ishan-002 requested changes

2022-02-21 20:19 UTC, Ishan-002 commented on docs/guides/effects_using_ParticleEffectComponent.rst
> +I have tweaked the `EditorCamera <https://rootex.readthedocs.io/en/latest/guides/editor_layout.html#editorcamera>`_ to get a better view of the scene.
Change ```I``` to ```We```

2022-02-21 20:19 UTC, Ishan-002 commented on docs/guides/effects_using_ParticleEffectComponent.rst
> +While Play, Stop and Play On Start are pretty self-explanatory, The follwoing explains the other options.
follwoing -> following

2022-02-21 23:15 UTC, Ishan-002 reviewed
None of the images/gifs are getting rendered. 
![image](https://user-images.githubusercontent.com/58972469/155036914-1b03b56b-4e5b-4cde-8b04-47d4d7d7a3c7.png)
Try to build the tutorial locally and then check it once.

2022-02-22 00:06 UTC, Ishan-002 commented on docs/guides/getting_started.rst
> +	making_HUD_using_ui-component
remove these

2022-02-22 14:03 UTC, angad-k commented on docs/guides/effects_using_ParticleEffectComponent.rst
> +=========
Use `---` to denote sections and `~~~` to denote subsections.

2022-02-22 19:06 UTC, Ishan-002 requested changes
There are some spacing problems in headings and after some images

2022-02-22 19:06 UTC, Ishan-002 commented on docs/guides/effects_using_ParticleEffectComponent.rst
> +We have added a demo effect which we get bundled with Effekseer 1.62b (Laser01.efkefc)
Add the link for Laser01.efkefc. I myself couldn't find it.

2022-02-22 19:06 UTC, Ishan-002 commented on docs/guides/effects_using_ParticleEffectComponent.rst
> +Add the effect by going to your scene's ParticleEffectComponent in the Inspector and clicking on the folder icon.
Maybe change ```folder icon``` to ```folder icon to select the file```

2022-02-25 19:52 UTC, Ishan-002 approved these changes

2022-02-25 19:53 UTC, merged