Transform system
sdslabs/Rootex pull request #580
Opened 2022-08-08 17:38 UTC by NehaGujar1

Implemented Transform System from Render System

2022-08-09 17:15 UTC, Bashar-Ahmed requested changes
Write proper commit messages
Remove `after` and Always write according to the format being used in the repository
In our case, use absolute tense eg: "Implement ......"
Squash the 2 linting commits into the first one.

2022-08-09 17:15 UTC, Bashar-Ahmed commented on rootex/framework/systems/transform_system.h
> +#include "render_system.h"
Only `system.h` and `transform_component.h` are needed here (with thier correct paths)
Delete the rest.

2022-08-09 17:15 UTC, Bashar-Ahmed commented on rootex/framework/systems/transform_system.cpp
> +#include "SimpleMath.h"
Only `transform_system.h` is needed

2022-08-09 17:15 UTC, Bashar-Ahmed commented on rootex/framework/systems/render_system.h
> +#include "framework/system.h"
Not needed

2022-08-09 17:15 UTC, Bashar-Ahmed commented on rootex/framework/systems/render_system.cpp
> +#include "transform_system.h"
This is already included in the header file, hence no need to include it again

2022-08-09 18:50 UTC, ChronicallySerious commented
Also just FYI: There's https://github.com/sdslabs/Rootex/blob/dev/CONTRIBUTING.md which has some instructions on how to create good commit messages

2022-08-26 14:16 UTC, Bashar-Ahmed approved these changes

2022-08-26 14:44 UTC, merged